### ISSUE TITLE
💡[Feature] 로그인 첫 화면 디자인

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Frontend#101]
## ✨ 이슈 체크리스트

- [x] 이슈 제목: [Feature] '기능 내용 상세'
- [x] Assignees, Label 추가

## 💡 기능 개요

- 로그인 첫 화면 디자인

## 📝 기능 상세 내용

- 로그인 첫 화면 디자인

## ✅ TODO

- [x] 로그인 첫 화면 디자인
