### ISSUE TITLE
🔨[Refactor] 가격 카테고리에서 하나만 선택되도록

### ISSUE THREAD

**Issue by hiwon2** [Art-Diary/Frontend#114]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label 추가

## 🔨 리팩토링 개요

- 가격 카테고리에서 하나를 선택하면 이미 선택된 것은 삭제되도록

## 📝 리팩토링 상세 내용

- 가격 카테고리에서 하나를 선택하면 이미 선택된 것은 삭제되도록

## ✅ TODO

- [x] 가격 카테고리에서 하나를 선택하면 이미 선택된 것은 삭제되도록
