### ISSUE TITLE
💡[Feature] 전시 리스트 화면에서 전시 상세정보 페이지 이동

### ISSUE THREAD

**Issue by hiwon2** [Art-Diary/Frontend#119]
## ✨ 이슈 체크리스트

- [x] 이슈 제목: [Feature] '기능 내용 상세'
- [x] Assignees, Label 추가

## 💡 기능 개요

- 전시리스트 화면에서 전시 상세정보 페이지 이동
- 
## 📝 기능 상세 내용

- 전시리스트 화면에서 전시 상세정보 페이지 이동

## ✅ TODO

- [x] TODO전시리스트 화면에서 전시 상세정보 페이지 이동
