### ISSUE TITLE
💡[Feature] 내 기록 컴포넌트 세분화

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Frontend#12]
## ✨ 이슈 체크리스트

- [x] 이슈 제목: [Feature] '기능 내용 상세'
- [x] Assignees, Label 추가

## 💡 기능 개요

- 내 기록 컴포넌트 세분화

## 📝 기능 상세 내용

- 내 기록 컴포넌트 세분화

## ✅ TODO

- [x] 내 기록 컴포넌트 세분화
