### ISSUE TITLE
🔨[Refactor] 검색 키워드 빈 문자열 검사 공통 함수 분리 & 사용자 정보 수정 공통 컴포넌트 분리

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Frontend#124]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label 추가

## 🔨 리팩토링 개요

- 검색 키워드 빈 문자열 검사 공통 함수 분리 & 사용자 정보 수정 공통 컴포넌트 분리

## 📝 리팩토링 상세 내용

- 검색 키워드 빈 문자열 검사 공통 함수 분리 & 사용자 정보 수정 공통 컴포넌트 분리

## ✅ TODO

- [x] 검색 키워드 빈 문자열 검사 공통 함수 분리
- [x] 사용자 정보 수정 공통 컴포넌트 분리
- [x] 탈퇴 후 로그인 화면으로 이동
- [x] 사용자 정보 수정 중 닉네임 작성 칸에 빈 문자열이 있을 경우 중복 확인이 되지 않도록 수정
