### ISSUE TITLE
🔨[Refactor] 로그인하는 사용자에 따라 api 요청의 헤더에 들어가는 userId가 달라질 수 있도록 구현

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Frontend#126]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label 추가

## 🔨 리팩토링 개요

- 로그인하는 사용자에 따라 api 요청의 헤더에 들어가는 userId가 달라질 수 있도록 구현

## 📝 리팩토링 상세 내용

- 로그인하는 사용자에 따라 api 요청의 헤더에 들어가는 userId가 달라질 수 있도록 구현
- 그에 따른 로그아웃과 탈퇴 시 로그인 페이지로 이동 되도록 수정하고
- 사용자 정보 조회 및 저장 방식도 수정

## ✅ TODO

- [x] 로그인하는 사용자에 따라 api 요청의 헤더에 들어가는 userId가 달라질 수 있도록 구현
