### ISSUE TITLE
🔨[Refactor] 검색 결과가 없는 경우 및 모달 외부 영역 터치 시 모달 닫기 처리, 캘린더에서 특정 날짜에 전시회 추가 이동 구현

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Frontend#131]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label 추가

## 🔨 리팩토링 개요

- 검색 결과가 없는 경우 및 모달 외부 영역 터치 시 모달 닫기 처리
- 캘린더에서 특정 날짜에 전시회 추가 이동 구현

## 📝 리팩토링 상세 내용

- 검색 결과가 없는 경우 결과가 없다는 메시지 표시
- 모달 내부를 제외한 외부 영역 터치 시 모달 닫기 처리
- 캘린더에서 특정 날짜에 전시회 추가 이동 구현

## ✅ TODO

- [x] 검색 결과 없을 때 처리
- [x] 모달 외부 영역 터치할 때 모달 닫히도록 처리
- [x] 캘린더에서 특정 날짜에 전시회 추가 이동 구현
