### ISSUE TITLE
🔨[Refactor] routes 경로 파일에 styled-component 및 반응형 디자인 적용

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Frontend#14]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label 추가

## 🔨 리팩토링 개요

- routes 경로 파일에 styled-component 및 반응형 디자인 적용

## 📝 리팩토링 상세 내용

- routes 경로 파일에 styled-component 및 반응형 디자인 적용

## ✅ TODO

- [x] routes 경로 파일에 styled-component 및 반응형 디자인 적용
