### ISSUE TITLE
🐞[Bug] 기록 날짜 선택 스크린의 모임 종류가 안 나오는 에러 해결

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Frontend#140]
## 🚨 이슈 체크리스트

- [x] 이슈 제목: [BUG] '버그 내용 상세'
- [x] Assignees, Label 추가

## 🐞 버그 개요

- 기록 날짜 선택 스크린의 모임 종류가 안 나오는 에러 해결

## 🐛 버그 상세 내용

- 기록 날짜 선택 스크린의 모임 종류가 안 나오는 에러 해결

## ✅ TODO

- [x] 기록 날짜 선택 스크린의 모임 종류가 안 나오는 에러 해결
