### ISSUE TITLE
🔨[Refactor] 데이터를 다시 요청하는 시점을 refetch와 react query의 invalidateQueries를 사용하여 처리

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Frontend#142]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label 추가

## 🔨 리팩토링 개요

- 데이터를 다시 요청하는 시점을 refetch와 react query의 invalidateQueries를 사용하여 처리

## 📝 리팩토링 상세 내용

- 데이터를 다시 요청하는 시점을 refetch와 react query의 invalidateQueries를 사용하여 처리

## ✅ TODO

- [x] 데이터를 다시 요청하는 시점을 refetch와 react query의 invalidateQueries를 사용하여 처리
