### ISSUE TITLE
💡[Feature] 전시회 상세정보에서 캘린더에 날짜 저장 페이지 이동

### ISSUE THREAD

**Issue by hiwon2** [Art-Diary/Frontend#143]
## ✨ 이슈 체크리스트

- [x] 이슈 제목: [Feature] '기능 내용 상세'
- [x] Assignees, Label 추가

## 💡 기능 개요

- 전시회 상세정보에서 캘린더에 날짜 저장 페이지 이동

## 📝 기능 상세 내용

- 전시회 상세정보에서 캘린더에 날짜 저장 페이지 이동
- 날짜 선택시 '캘린더 이동' 모달 띄우기

## ✅ TODO

- [x] 전시회 상세정보에서 캘린더에 날짜 저장 페이지 이동
