### ISSUE TITLE
🐞[Bug] 모임 메인 화면과 관련된 화면 중 오류가 발생할 때 헤더가 없어지는 화면들 수정

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Frontend#146]
## 🚨 이슈 체크리스트

- [x] 이슈 제목: [BUG] '버그 내용 상세'
- [x] Assignees, Label 추가

## 🐞 버그 개요

- 모임 메인 화면과 관련된 화면 중 오류가 발생할 때 헤더가 없어지는 화면들 수정
## 🐛 버그 상세 내용

- 모임 메인 화면과 관련된 화면 중 오류가 발생할 때 헤더가 없어지는 화면들 수정
## ✅ TODO

- [x] 모임 메인 화면과 관련된 화면 중 오류가 발생할 때 헤더가 없어지는 화면들 수정

**Comment by cofls980** [comment]
모임 메인 화면이 아니라 전시 메이트 탭 메인 화면이었음
