### ISSUE TITLE
💡[Feature] 앱 종료 시 뒤로가기 두 번 클릭

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Frontend#173]
## ✨ 이슈 체크리스트

- [x] 이슈 제목: [Feature] '기능 내용 상세'
- [x] Assignees, Label 추가

## 💡 기능 개요

- 앱 종료 시 뒤로가기 두 번 클릭

## 📝 기능 상세 내용

- 앱 종료 시 뒤로가기 두 번 클릭

## ✅ TODO

- [x] 앱 종료 시 뒤로가기 두 번 클릭
