### ISSUE TITLE
💡[Feature] 해당 전시 갤러리 홈페이지로 이동

### ISSUE THREAD

**Issue by hiwon2** [Art-Diary/Frontend#175]
## ✨ 이슈 체크리스트

- [x] 이슈 제목: [Feature] '기능 내용 상세'
- [x] Assignees, Label 추가

## 💡 기능 개요

- 해당 전시회에서 홈페이지 버튼 누르면 갤러리 홈페이지(전시회 세부정보 상세페이지) 로 이동

## 📝 기능 상세 내용

- 해당 전시회에서 홈페이지 버튼 누르면 갤러리 홈페이지(전시회 세부정보 상세페이지) 로 이동

## ✅ TODO

- [ ]해당 전시회에서 홈페이지 버튼 누르면 갤러리 홈페이지(전시회 세부정보 상세페이지) 로 이동
