### ISSUE TITLE
🔨[Refactor] 푸시 알림 설정과 회원 탈퇴 화면 반응형 디자인 적용

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Frontend#180]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label 추가

## 🔨 리팩토링 개요

- 푸시 알림 설정과 회원 탈퇴 화면 반응형 디자인 적용

## 📝 리팩토링 상세 내용

- 푸시 알림 설정과 회원 탈퇴 화면 반응형 디자인 적용

## ✅ TODO

- [x] 푸시 알림 설정과 회원 탈퇴 화면 반응형 디자인 적용
