### ISSUE TITLE
🔨[Refactor] 전시회 상세 페이지에서 캘린더 이동 해결

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Frontend#190]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label 추가

## 🔨 리팩토링 개요

- 전시회 상세 페이지에서 캘린더 이동 해결

## 📝 리팩토링 상세 내용

- 캘린더 이동 안되는 문제
- 캘린더 이동 후 선택한 날짜 보여주기
- 날짜 선택 후 취소 눌렀다가 날짜 선택 페이지로 가면 바로 전에 선택한 날짜 표시되어 있지 않는 문제

## ✅ TODO

 * [x] 캘린더 이동 안되는 문제
 * [x] 캘린더 이동 후 선택한 날짜 보여주기
 * [x] 날짜 선택 후 취소 눌렀다가 날짜 선택 페이지로 가면 바로 전에 선택한 날짜 표시되어 있지 않는 문제
