### ISSUE TITLE
🐞[Bug] 전시회 검색할 때 같은 키워드 연속 검색 시 초기화되는 문제

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Frontend#193]
## 🚨 이슈 체크리스트

- [x] 이슈 제목: [BUG] '버그 내용 상세'
- [x] Assignees, Label 추가

## 🐞 버그 개요

- 전시회 검색할 때 같은 키워드 연속 검색 시 초기화되는 문제

## 🐛 버그 상세 내용

- 전시회 검색할 때 같은 키워드 연속 검색 시 초기화되는 문제

## ✅ TODO

- [x] 전시회 검색할 때 같은 키워드 연속 검색 시 초기화되는 문제
