### ISSUE TITLE
🔨[Refactor] 동일한 이메일을 가진 소셜 로그인 통합 관련 모달 구현

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Frontend#194]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label 추가

## 🔨 리팩토링 개요

- 동일한 이메일을 가진 소셜 로그인 통합 관련 모달 구현

## 📝 리팩토링 상세 내용

- 동일한 이메일을 가진 소셜 로그인 통합 관련 모달 구현

## ✅ TODO

- [x] 동일한 이메일을 가진 소셜 로그인 통합 관련 모달 구현
