### ISSUE TITLE
🐞[Bug] 전시회 상세 페이지 리뷰 수정 바로 반영되도록 수정

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Frontend#197]
## 🚨 이슈 체크리스트

- [x] 이슈 제목: [BUG] '버그 내용 상세'
- [x] Assignees, Label 추가

## 🐞 버그 개요

- 전시회 상세 페이지 리뷰 수정 바로 반영되도록 수정

## 🐛 버그 상세 내용

- 전시회 상세 페이지 리뷰 수정 바로 반영되도록 수정

## ✅ TODO

- [x] 전시회 상세 페이지 리뷰 수정 바로 반영되도록 수정
