### ISSUE TITLE
🔨[Refactor] 폴더 이름 변경

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Frontend#203]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label 추가

## 🔨 리팩토링 개요

- 폴더 이름 변경

## 📝 리팩토링 상세 내용

- 폴더 이름 변경

## ✅ TODO

- [x] 폴더 이름 변경
