### ISSUE TITLE
🔨[Refactor] 내 기록과 캘린더 관련 api 중 새로운 전시방문 및 기록 엔티티가 적용된 반환 값으로 수정

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Frontend#205]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label 추가

## 🔨 리팩토링 개요

- 내 기록과 캘린더 관련 api 중 새로운 전시방문 및 기록 엔티티가 적용된 반환 값으로 수정

## 📝 리팩토링 상세 내용

- 내 기록과 캘린더 관련 api 중 새로운 전시방문 및 기록 엔티티가 적용된 반환 값으로 수정

## ✅ TODO

- [x] 내 기록 관련 api 중 새로운 전시방문 및 기록 엔티티가 적용된 반환 값으로 수정
- [x] 캘린더 관련 api 중 새로운 전시방문 및 기록 엔티티가 적용된 반환 값으로 수정
