### ISSUE TITLE
🐞[Bug] 모임의 전시회 기록 수정 중 방문 날짜 선택 오류

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Frontend#207]
## 🚨 이슈 체크리스트

- [x] 이슈 제목: [BUG] '버그 내용 상세'
- [x] Assignees, Label 추가

## 🐞 버그 개요

- 모임의 전시회 기록 수정 중 방문 날짜 선택 오류

## 🐛 버그 상세 내용

- 모임의 전시회 기록 수정 중 방문 날짜 선택 오류

## ✅ TODO

- [ ] 모임의 전시회 기록 수정 중 방문 날짜 선택 오류
