### ISSUE TITLE
💡[Feature] 요청 헤더에 jwt 추가

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Frontend#208]
## ✨ 이슈 체크리스트

- [x] 이슈 제목: [Feature] '기능 내용 상세'
- [x] Assignees, Label 추가

## 💡 기능 개요

- 요청 헤더에 jwt 추가

## 📝 기능 상세 내용

- 요청 헤더에 jwt 추가

## ✅ TODO

- [x] 요청 헤더에 jwt 추가
