### ISSUE TITLE
🔨[Refactor] 점을 포함한 형식의 날짜 반환 데이터 반영

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Frontend#210]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label 추가

## 🔨 리팩토링 개요

- 점을 포함한 형식의 날짜 반환 데이터 반영

## 📝 리팩토링 상세 내용

- 점을 포함한 형식의 날짜 반환 데이터 반영

## ✅ TODO

- [x] 점을 포함한 형식의 날짜 반환 데이터 반영
