### ISSUE TITLE
🔨[Refactor] 모임 셀렉터 너비 변경 및 한마디 입력 칸 밀림 현상 해결

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Frontend#211]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label 추가

## 🔨 리팩토링 개요

- 모임 셀렉터 너비 변경 및 한마디 입력 칸 밀림 현상 해결

## 📝 리팩토링 상세 내용

- 모임 셀렉터 너비 변경 및 한마디 입력 칸 밀림 현상 해결
## ✅ TODO

- [x] 모임 셀렉터 너비 변경 및 한마디 입력 칸 밀림 현상 해결
