### ISSUE TITLE
🔨[Refactor] base64 형식 사진 데이터에서 s3 사진 url로 변경으로 인한 수정

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Frontend#214]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label 추가

## 🔨 리팩토링 개요

- base64 형식 사진 데이터에서 s3 사진 url로 변경으로 인한 수정

## 📝 리팩토링 상세 내용

- base64 형식 사진 데이터에서 s3 사진 url로 변경으로 인한 수정

## ✅ TODO

- [x] base64 형식 사진 데이터에서 s3 사진 url로 변경으로 인한 수정
