### ISSUE TITLE
🔨[Refactor] 기록 내용 중 첨부 사진 데이터 추가

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Frontend#216]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label 추가

## 🔨 리팩토링 개요

- 기록 내용 중 첨부 사진 데이터 추가

## 📝 리팩토링 상세 내용

- 기록 내용 작성 중 첨부 사진이 들어가는 부분에 표시하고
- 사진 데이터를 multipartfile 형태에 맞춰 formdata에 files라는 이름으로 추가.

- 기록 내용 불러올 때는 첨부 사진이 aws s3 url로 들어가 있어, RickEditor 컴포넌트 대신 RenderHtml 컴포넌트 사용으로 바꿔 aws s3 url이 포함된 기록 내용 렌더링.

## ✅ TODO

- [x] 기록 내용 중 첨부 사진 데이터 추가
