### ISSUE TITLE
💡[Feature] 페이지 새로고침 추가 및 커스텀 touchable로 교체

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Frontend#217]
## ✨ 이슈 체크리스트

- [x] 이슈 제목: [Feature] '기능 내용 상세'
- [x] Assignees, Label 추가

## 💡 기능 개요

- 페이지 새로고침 추가 및 커스텀 touchable로 교체

## 📝 기능 상세 내용

- 페이지 새로고침 추가 및 커스텀 touchable로 교체

## ✅ TODO

- [x] 페이지 새로고침 추가 및 커스텀 touchable로 교체
