### ISSUE TITLE
🔨[Refactor] 앨범 접근 권한 요청과 알림 허용 권한 요청 수정

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Frontend#220]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label 추가

## 🔨 리팩토링 개요

- 앨범 접근 권한 요청과 알림 허용 권한 요청 수정

## 📝 리팩토링 상세 내용

- 앨범 접근 권한 요청과 알림 허용 권한 요청 수정

## ✅ TODO

- [x] 앨범 접근 권한 요청과 알림 허용 권한 요청 수정
