### ISSUE TITLE
🔨[Refactor] 전시회 상세 코드 분리 및 소개 html 렌더링 사용

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Frontend#226]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label 추가

## 🔨 리팩토링 개요

- 전시회 상세 코드 분리 및 소개 html 렌더링 사용

## 📝 리팩토링 상세 내용

- 전시회 상세 코드 분리 및 소개 html 렌더링 사용

## ✅ TODO

- [x] 전시회 상세 코드 분리 및 소개 html 렌더링 사용
