### ISSUE TITLE
🔨[Refactor] 전시회 상세 페이지 아이콘 이동

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Frontend#230]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label 추가

## 🔨 리팩토링 개요

- 전시회 상세 페이지 아이콘 이동

## 📝 리팩토링 상세 내용

- 전시회 상세 페이지 아이콘 이동

## ✅ TODO

- [x] 전시회 상세 페이지 아이콘 이동
