### ISSUE TITLE
🔨[Refactor] 에디터에 사진 추가 시 스크롤되지 않는 것 해결

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Frontend#234]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label 추가

## 🔨 리팩토링 개요

- 에디터에 사진 추가 시 스크롤되지 않는 것 해결

## 📝 리팩토링 상세 내용

- 에디터에 사진 추가 시 스크롤되지 않는 것 해결

## ✅ TODO

- [x] 에디터에 사진 추가 시 스크롤되지 않는 것 해결
