### ISSUE TITLE
💡[Feature] 관리자 전시회 등록

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Frontend#252]
## ✨ 이슈 체크리스트

- [x] 이슈 제목: [Feature] '기능 내용 상세'
- [x] Assignees, Label 추가

## 💡 기능 개요

- 관리자 전시회 등록

## 📝 기능 상세 내용

- 관리자 전시회 등록

## ✅ TODO

- [x] 관리자 전시회 등록
