### ISSUE TITLE
🐞[Bug] 관리자인지 확인 후 관리자용 전시회 등록 페이지 표시 추가

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Frontend#258]
## 🚨 이슈 체크리스트

- [x] 이슈 제목: [BUG] '버그 내용 상세'
- [x] Assignees, Label 추가

## 🐞 버그 개요

- 관리자인지 확인 후 관리자용 전시회 등록 페이지 표시 추가

## 🐛 버그 상세 내용

- 관리자인지 확인 후 관리자용 전시회 등록 페이지 표시 추가

## ✅ TODO

- [x] 관리자인지 확인 후 관리자용 전시회 등록 페이지 표시 추가
