### ISSUE TITLE
💡[Feature] 전시회 혼자 방문 날짜 추가 화면

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Frontend#26]
## ✨ 이슈 체크리스트

- [x] 이슈 제목: [Feature] '기능 내용 상세'
- [x] Assignees, Label 추가

## 💡 기능 개요

- 전시회 혼자 방문 날짜 추가 화면

## 📝 기능 상세 내용

- 전시회 혼자 방문 날짜 추가 화면

## ✅ TODO

- [x] 전시회 혼자 방문 날짜 추가 화면
