### ISSUE TITLE
💡[Feature] 관리자의 등록된 전시회 삭제 구현

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Frontend#264]
## ✨ 이슈 체크리스트

- [x] 이슈 제목: [Feature] '기능 내용 상세'
- [x] Assignees, Label 추가

## 💡 기능 개요

- 관리자의 등록된 전시회 삭제 구현

## 📝 기능 상세 내용

- 관리자의 등록된 전시회 삭제 구현

## ✅ TODO

- [ ] 관리자의 등록된 전시회 삭제 구현
