### ISSUE TITLE
🔨[Refactor] 관리자의 등록된 전시회 삭제 아이콘 없애기

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Frontend#266]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label 추가

## 🔨 리팩토링 개요

- 관리자의 등록된 전시회 삭제 아이콘 없애기

## 📝 리팩토링 상세 내용

- 관리자용 등록 전시회 삭제 아이콘 없애고, 전시회 목록의 마지막 아이템에 아래 공간 추가

## ✅ TODO

- [x] 관리자의 등록된 전시회 삭제 아이콘 없애기
