### ISSUE TITLE
🔨[Refactor] 내 기록 테스트의 수정 사항 반영

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Frontend#269]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label 추가

## 🔨 리팩토링 개요

- 내 기록 테스트의 수정 사항 반영

## 📝 리팩토링 상세 내용

- 기록 추가 시 선택할 날짜가 없는 경우 페이지 메시지 추가
- 기록 작성 폼의 필수데이터 표시 및 메시지 추가
- 기록 작성 폼 하단 버튼 색을 분홍색으로 변경
- 썸네일의 선택한 사진 삭제 버튼 추가
- 기록 수정 시 방문 날짜 섹션 옆에 “전시회 방문 날짜를 수정할 수 있습니다.” 설명 추가
- 기록 수정 완료 후, 해당 기록 페이지로 이동하도록 수정
- 기록 수정/삭제 모달 취소 버튼 기능 추가
- 한 전시회에 대한 기록을 모두 삭제하면 내 기록 페이지로 이동하도록 수정

## ✅ TODO

- [x] 내 기록 테스트의 수정 사항 반영
