### ISSUE TITLE
🔨[Refactor] 개인 일정이 없는 경우 날짜 추가했을 때 추가된 화면 바로 보이도록 수정

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Frontend#271]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label 추가

## 🔨 리팩토링 개요

- 개인 일정이 없는 경우 날짜 추가했을 때 추가된 화면 바로 보이도록 수정

## 📝 리팩토링 상세 내용

- “개인” 선택하고 방문 날짜가 아무것도 없을 경우, “추가” 버튼을 통해 날짜 추가한 후, 날짜 선택화면으로 돌아갔을 때 추가한 날짜가 바로 보여지도록 수정

## ✅ TODO

- [x] 개인 일정이 없는 경우 날짜 추가했을 때 추가된 화면 바로 보이도록 수정
