### ISSUE TITLE
🔨[Refactor] 전시회 상세 페이지를 통한 방문 날짜 추가 모달 수정

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Frontend#277]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label 추가

## 🔨 리팩토링 개요

- 전시회 상세 페이지를 통한 방문 날짜 추가 모달 수정

## 📝 리팩토링 상세 내용

- 날짜 선택 후 버튼 클릭 시 해당 날짜로 추가할지 확인 모달 추가
    - 취소 버튼 또는 모달 밖 영역 누르면 날짜 추가 취소
- 추가 버튼 누르면 캘린더로 이동 여부 모달 열고, 모달 밖 영역 눌렀을 때 달력에 날짜가 추가된 상태로 모달만 닫히도록 수정

## ✅ TODO

- [x] 전시회 상세 페이지를 통한 방문 날짜 추가 모달 수정
