### ISSUE TITLE
🐞[Bug] 전시회 상세 페이지의 좋아요 하트 연속 안 눌림 오류 해결

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Frontend#278]
## 🚨 이슈 체크리스트

- [x] 이슈 제목: [BUG] '버그 내용 상세'
- [x] Assignees, Label 추가

## 🐞 버그 개요

- 전시회 상세 페이지의 좋아요 하트 연속 안 눌림 오류 해결

## 🐛 버그 상세 내용

- 전시회 상세 페이지의 좋아요 하트 연속 안 눌림 오류 해결

## ✅ TODO

- [x] 전시회 상세 페이지의 좋아요 하트 연속 안 눌림 오류 해결
