### ISSUE TITLE
🔨[Refactor] 업데이트한 데이터 적용 및 zustand 사용 세분화

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Frontend#28]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label 추가

## 🔨 리팩토링 개요

- 업데이트한 데이터 적용 및 zustand 사용 세분화

## 📝 리팩토링 상세 내용

- 업데이트한 데이터 적용 및 zustand 사용 세분화

## ✅ TODO

- [x] 업데이트한 데이터 적용 및 zustand 사용 세분화
