### ISSUE TITLE
🔨[Refactor] 기록 작성에 필요한 전시회 선택과 방문 날짜 선택 로직 변경

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Frontend#281]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label 추가

## 🔨 리팩토링 개요

- 기록 작성에 필요한 전시회 선택과 방문 날짜 선택 로직 변경

## 📝 리팩토링 상세 내용

- 기록 작성에 필요한 전시회 선택과 방문 날짜 선택 로직 변경

## ✅ TODO

- [x] 기록 작성에 필요한 전시회 선택과 방문 날짜 선택 로직 변경
