### ISSUE TITLE
🔨[Refactor] 탈퇴한 사용자 닉네임을 회색으로 보이게 처리

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Frontend#287]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label 추가

## 🔨 리팩토링 개요

- 탈퇴한 사용자 닉네임을 회색으로 보이게 처리

## 📝 리팩토링 상세 내용

- 탈퇴한 사용자 닉네임을 회색으로 보이게 처리

## ✅ TODO

- [x] 탈퇴한 사용자 닉네임을 회색으로 보이게 처리
