### ISSUE TITLE
🔨[Refactor] 캘린더의 특정 날짜에 전시회 추가 로직 변경

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Frontend#289]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label 추가

## 🔨 리팩토링 개요

- 캘린더의 특정 날짜에 전시회 추가 로직 변경

## 📝 리팩토링 상세 내용

- 캘린더의 특정 날짜에 전시회 추가 로직 변경

## ✅ TODO

- [x] 캘린더의 특정 날짜에 전시회 추가 로직 변경

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modified CalendarScreen.tsx to improve the logic for adding exhibitions to specific dates. Updated ExhAddVisitDateCalendarFrame.tsx to support the new logic. Adjusted related components and state management.

You can review changes in this commit: https://github.com/mnmnk43434/Art-Diary-Frontend-289/commit/6f17555a36e700e592d61d6fba8260628321183d.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
