### ISSUE TITLE
💡[Feature] 내 전시회 목록에 전시회 추가를 위한 검색 화면 구현

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Frontend#29]
## ✨ 이슈 체크리스트

- [x] 이슈 제목: [Feature] '기능 내용 상세'
- [x] Assignees, Label 추가

## 💡 기능 개요

- 내 전시회 목록에 전시회 추가를 위한 검색 화면

## 📝 기능 상세 내용

- 내 전시회 목록에 전시회 추가를 위한 검색 화면

## ✅ TODO

- [x] 내 전시회 목록에 전시회 추가를 위한 검색 화면
