### ISSUE TITLE
🔨[Refactor] 기록 수정과 삭제 모달 디자인 변경

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Frontend#290]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label 추가

## 🔨 리팩토링 개요

- 기록 수정과 삭제 모달 디자인 변경

## 📝 리팩토링 상세 내용

- 기록 수정과 삭제 모달 디자인 변경

## ✅ TODO

- [x] 기록 수정과 삭제 모달 디자인 변경
