### ISSUE TITLE
🐞[Bug] 기록 수정 시 모임에서 개인 방문 날짜로 변경 시 기존에 선택한 날짜 선택 해제 불가 오류

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Frontend#296]
## 🚨 이슈 체크리스트

- [x] 이슈 제목: [BUG] '버그 내용 상세'
- [x] Assignees, Label 추가

## 🐞 버그 개요

- 기록 수정 시 모임에서 개인 방문 날짜로 변경 시 기존에 선택한 날짜 선택 해제 불가 오류

## 🐛 버그 상세 내용

- 기록 수정 시 모임에서 개인 방문 날짜로 변경 시 기존에 선택한 날짜 선택 해제 불가 오류

[추가]
- 캘린더 탭의 달력 사이드에 여백 추가하기
- 달력의 날짜 하이라이트 기본 색깔 수정하기

## ✅ TODO

- [x] 기록 수정 시 모임에서 개인 방문 날짜로 변경 시 기존에 선택한 날짜 선택 해제 불가 오류
