### ISSUE TITLE
🔨[Refactor] 캘린더 탭의 달력 사이드에 여백 추가 및 달력의 날짜 하이라이트 기본 색깔 수정

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Frontend#297]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label 추가

## 🔨 리팩토링 개요

- 캘린더 탭의 달력 사이드에 여백 추가하기

## 📝 리팩토링 상세 내용

- 캘린더 탭의 달력 사이드에 여백 추가하기
- 달력의 날짜 하이라이트 기본 색깔 수정하기

## ✅ TODO

- [x] 캘린더 탭의 달력 사이드에 여백 추가하기
- [x] 달력의 날짜 하이라이트 기본 색깔 수정
