### ISSUE TITLE
🔨[Refactor] 전시 메이트 추가 페이지를 모달로 변경

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Frontend#299]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label 추가

## 🔨 리팩토링 개요

- 전시 메이트 추가 페이지를 모달로 변경

## 📝 리팩토링 상세 내용

- 전시 메이트 추가 페이지를 모달로 변경

## ✅ TODO

- [x] 전시 메이트 추가 페이지를 모달로 변경
