### ISSUE TITLE
🔨[Refactor] 내 프로필 수정 폼 디자인 변경

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Frontend#308]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label 추가

## 🔨 리팩토링 개요

- 내 프로필 수정 폼 디자인 변경

## 📝 리팩토링 상세 내용

- 내 프로필 수정 폼 디자인 변경

## ✅ TODO

- [x] 내 프로필 수정 폼 디자인 변경
