### ISSUE TITLE
🔨[Refactor] 등록 전시회 수정 정보 바로 반영 안되는 문제 해결 및 컴포넌트 정리

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Frontend#312]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label 추가

## 🔨 리팩토링 개요

- 등록 전시회 수정 정보 바로 반영 안되는 문제 해결 및 컴포넌트 정리

## 📝 리팩토링 상세 내용

- 등록 전시회 수정 정보 바로 반영 안되는 문제 해결 및 컴포넌트 정리

## ✅ TODO

- [x] 등록 전시회 수정 정보 바로 반영 안되는 문제 해결 및 컴포넌트 정리
