### ISSUE TITLE
🔨[Refactor] 수정된 3가지 등록 현황 반영

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Frontend#313]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label 추가

## 🔨 리팩토링 개요

- 수정된 3가지 등록 현황 반영

## 📝 리팩토링 상세 내용

- 수정된 3가지 등록 현황 반영

## ✅ TODO

- [x] 수정된 3가지 등록 현황 반영
