### ISSUE TITLE
🔨[Refactor] 등록할 전시회 목록이 비어있을 경우 처리 및 새로 등록 버튼 추가

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Frontend#314]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label 추가

## 🔨 리팩토링 개요

- 등록할 전시회 목록이 비어있을 경우 처리 및 새로 등록 버튼 추가

## 📝 리팩토링 상세 내용

- 등록할 전시회 목록이 비어있을 경우 처리 및 새로 등록 버튼 추가

## ✅ TODO

- [x] 등록할 전시회 목록이 비어있을 경우 처리 및 새로 등록 버튼 추가
