### ISSUE TITLE
💡[Feature] 모임 초대 완료 푸시 알림 클릭 시 모임으로 이동하는 로직 추가

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Frontend#317]
## ✨ 이슈 체크리스트

- [x] 이슈 제목: [Feature] '기능 내용 상세'
- [x] Assignees, Label 추가

## 💡 기능 개요

- 모임 초대 완료 푸시 알림 클릭 시 모임으로 이동하는 로직 추가

## 📝 기능 상세 내용

- 모임 초대 완료 푸시 알림 클릭 시 모임으로 이동하는 로직 추가

## ✅ TODO

- [ ] 모임 초대 완료 푸시 알림 클릭 시 모임으로 이동하는 로직 추가
