### ISSUE TITLE
🔨[Refactor] 푸시 알림 종류 5가지로 변경

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Frontend#321]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label 추가

## 🔨 리팩토링 개요

- 푸시 알림 종류 5가지로 변경

## 📝 리팩토링 상세 내용

- 좋아요한 전시회 시작인/마감일 알림
- 혼자 가는 전시회 날짜 알림
- 모임에서 가는 전시회 날짜 알림
- 새로운 모임 알림
- 모임에서 추가된 전시회 알림

## ✅ TODO

- [x] 푸시 알림 종류 5가지로 변경
