### ISSUE TITLE
🔨[Refactor] 로딩 모달 및 오류 메시지 수정하기

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Frontend#326]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label 추가

## 🔨 리팩토링 개요

- 로딩 모달 및 오류 메시지 수정하기

## 📝 리팩토링 상세 내용

- 로딩 모달 및 오류 메시지 수정하기

## ✅ TODO

- [x] 로딩 모달 및 오류 메시지 수정하기
