### ISSUE TITLE
🐞[Bug] 홈 화면에서 뒤로가기 해결

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Frontend#33]
## 🚨 이슈 체크리스트

- [x] 이슈 제목: [BUG] '버그 내용 상세'
- [x] Assignees, Label 추가

## 🐞 버그 개요

- 홈 화면에서 뒤로가기 해결

## 🐛 버그 상세 내용

- 홈 화면의 전시회 탭 포함 모든 탭에서 뒤로가기하면 전시회 탭으로 이동 후 어플 종료되는 현상 해결

## ✅ TODO

- [x] 홈 화면에서 뒤로가기 해결
