### ISSUE TITLE
🐞[Bug] 한 전시회에 대하여 캘린더에 저장된 날짜 조회 응답 데이터 오류 수정에 따른 코드 수정

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Frontend#35]
## 🚨 이슈 체크리스트

- [x] 이슈 제목: [BUG] '버그 내용 상세'
- [x] Assignees, Label 추가

## 🐞 버그 개요

- 한 전시회에 대하여 캘린더에 저장된 날짜 조회 응답 데이터 오류 수정에 따른 코드 수정

## 🐛 버그 상세 내용

- 한 전시회에 대하여 캘린더에 저장된 날짜 조회 응답 데이터 오류 수정에 따른 코드 수정

## ✅ TODO

- [x] 한 전시회에 대하여 캘린더에 저장된 날짜 조회 응답 데이터 오류 수정에 따른 코드 수정
