### ISSUE TITLE
🔨[Refactor] SearchExhList 컴포넌트에서 ExhItem 분리

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Frontend#37]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label 추가

## 🔨 리팩토링 개요

- SearchExhList 컴포넌트에서 ExhItem 분리

## 📝 리팩토링 상세 내용

- SearchExhList 컴포넌트에서 ExhItem 분리

## ✅ TODO

- [x] SearchExhList 컴포넌트에서 ExhItem 분리
