### ISSUE TITLE
🔨[Refactor] ExhItemView에 children 추가

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Frontend#39]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label 추가

## 🔨 리팩토링 개요

- ExhItemView에 children 추가

## 📝 리팩토링 상세 내용

- ExhItemView에 children 추가

## ✅ TODO

- [x] ExhItemView에 children 추가
