### ISSUE TITLE
💡[Feature] 참고 용 내 기록 화면 목업 완성

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Frontend#4]
## ✨ 이슈 체크리스트

- [x] 이슈 제목: [Feature] '기능 내용 상세'
- [x] Assignees, Label 추가

## 💡 기능 개요

- 참고 용 내 기록 화면 목업 완성

## 📝 기능 상세 내용

- 참고 용 내 기록 화면 목업 완성

## ✅ TODO

- [x] 참고 용 내 기록 화면 목업 완성
