### ISSUE TITLE
🔨[Refactor] 확인 메시지 모달을 Toast 패키지 사용으로 변경

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Frontend#45]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label 추가

## 🔨 리팩토링 개요

- 확인 메시지 모달을 Toast 패키지 사용으로 변경

## 📝 리팩토링 상세 내용

- 확인 메시지 모달을 Toast 패키지 사용으로 변경

## ✅ TODO

- [x] 확인 메시지 모달을 Toast 패키지 사용으로 변경
