### ISSUE TITLE
🔨[Refactor] 업로드 사진 압축 추가 구현

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Frontend#48]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label 추가

## 🔨 리팩토링 개요

- 업로드 사진 압축 추가 구현

## 📝 리팩토링 상세 내용

- 업로드 사진 압축 추가 구현

## ✅ TODO

- [x] 업로드 사진 압축 추가 구현
