### ISSUE TITLE
🔨[Refactor] 기록 내용 작성 중 줄마다 밑줄 추가하기

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Frontend#50]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label 추가

## 🔨 리팩토링 개요

- 기록 내용 작성 중 줄마다 밑줄 추가하기

## 📝 리팩토링 상세 내용

- 기록 내용 작성 중 줄마다 밑줄 추가하기

## ✅ TODO

- [ ] 기록 내용 작성 중 줄마다 밑줄 추가하기
