### ISSUE TITLE
💡[Feature] 전시회 목록 스크린

### ISSUE THREAD

**Issue by hiwon2** [Art-Diary/Frontend#54]
## ✨ 이슈 체크리스트

- [x] 이슈 제목: [Feature] '기능 내용 상세'
- [x] Assignees, Label 추가

## 💡 기능 개요

- 전시회 목록 스크린

## 📝 기능 상세 내용

- 네비게이션바의 전시회를 누르면 나오는 화면
- 전시회 정보 목록, 좋아하는 전시회 하트 표시,분류,검색,캘린더 아이콘 표시 

## ✅ TODO

- [x] 전시회 목록 화면 만들기
