### ISSUE TITLE
💡[Feature] 전시회 방문 날짜 '기억 안 남' 추가 구현

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Frontend#56]
## ✨ 이슈 체크리스트

- [x] 이슈 제목: [Feature] '기능 내용 상세'
- [x] Assignees, Label 추가

## 💡 기능 개요

- 전시회 방문 날짜 '기억 안 남' 추가 구현

## 📝 기능 상세 내용

- 전시회 방문 날짜 '기억 안 남' 추가 구현

## ✅ TODO

- [x] 전시회 방문 날짜 '기억 안 남' 추가 구현
