### ISSUE TITLE
💡[Feature] 전시회 목록 스크린에 있는 좋아요 기능 구현

### ISSUE THREAD

**Issue by hiwon2** [Art-Diary/Frontend#59]
## ✨ 이슈 체크리스트

- [x] 이슈 제목: [Feature] '기능 내용 상세'
- [x] Assignees, Label 추가

## 💡 기능 개요

- 좋아요 생성 및 삭제

## 📝 기능 상세 내용

- 좋아요 생성 및 삭제

## ✅ TODO

- [ ] 좋아요 생성 및 삭제 구현
