### ISSUE TITLE
💡[Feature] 서버와 연동하여 참고 용으로 "내 기록의 전시회 목록 조회" 요청하고 데이터 처리

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Frontend#6]
## ✨ 이슈 체크리스트

- [x] 이슈 제목: [Feature] '기능 내용 상세'
- [x] Assignees, Label 추가

## 💡 기능 개요

- 서버와 연동하여 참고 용으로 "내 기록의 전시회 목록 조회" 요청하고 데이터 처리

## 📝 기능 상세 내용

- 서버와 연동하여 참고 용으로 "내 기록의 전시회 목록 조회" 요청하고 데이터 처리

## ✅ TODO

- [x] 서버와 연동하여 참고 용으로 "내 기록의 전시회 목록 조회" 요청하고 데이터 처리
