### ISSUE TITLE
💡[Feature] 전시 분류 카테고리 모달 구현

### ISSUE THREAD

**Issue by hiwon2** [Art-Diary/Frontend#69]
## ✨ 이슈 체크리스트

- [x] 이슈 제목: [Feature] '기능 내용 상세'
- [x] Assignees, Label 추가

## 💡 기능 개요

- 전시 분류 카테고리 모달 구현

## 📝 기능 상세 내용

- 전시 분류 카테고리 모달 구현
- 선택된 분류 값, 전시회 스크린으로 이동시 전달
- 해당 전시회만 데이터 불러오기

## ✅ TODO

- [x] 전시 분류 카테고리 모달 구현
