### ISSUE TITLE
💡[Feature] 캘린더에서 전시회 선택 시 기록 목록 조회 화면으로 이동 구현

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Frontend#76]
## ✨ 이슈 체크리스트

- [x] 이슈 제목: [Feature] '기능 내용 상세'
- [x] Assignees, Label 추가

## 💡 기능 개요

- 캘린더에서 전시회 선택 시 기록 목록 조회 화면으로 이동 구현

## 📝 기능 상세 내용

- 캘린더에서 전시회 선택 시 기록 목록 조회 화면으로 이동 구현

## ✅ TODO

- [x] 캘린더에서 전시회 선택 시 기록 목록 조회 화면으로 이동 구현
