### ISSUE TITLE
🔨[Refactor] CustomCalendar의 props 중 markedDate 타입 변경으로 인한 코드 수정

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Frontend#77]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label 추가

## 🔨 리팩토링 개요

- CustomCalendar의 props 중 markedDate 타입 변경으로 인한 코드 수정

## 📝 리팩토링 상세 내용

- CustomCalendar의 props 중 markedDate 타입 변경으로 인한 코드 수정

## ✅ TODO

- [x] CustomCalendar의 props 중 markedDate 타입 변경으로 인한 코드 수정
