### ISSUE TITLE
🔨[Refactor] 백엔드의 gatheringExhId에서 gatherExhId로의 변경으로 인한 수정

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Frontend#79]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label 추가

## 🔨 리팩토링 개요

- 백엔드의 gatheringExhId에서 gatherExhId로의 변경으로 인한 수정

## 📝 리팩토링 상세 내용

- 백엔드의 gatheringExhId에서 gatherExhId로의 변경으로 인한 수정

## ✅ TODO

- [x] 백엔드의 gatheringExhId에서 gatherExhId로의 변경으로 인한 수정
