### ISSUE TITLE
💡[Feature] 내 기록의 전시회에 대한 간단한 zustand 적용 및 query-key-factory 적용

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Frontend#8]
## ✨ 이슈 체크리스트

- [x] 이슈 제목: [Feature] '기능 내용 상세'
- [x] Assignees, Label 추가

## 💡 기능 개요

- 내 기록의 전시회에 대한 간단한 zustand 적용 및 query-key-factory 적용

## 📝 기능 상세 내용

- 내 기록의 전시회에 대한 간단한 zustand 적용 및 query-key-factory 적용

## ✅ TODO

- [x] 내 기록의 전시회에 대한 간단한 zustand 적용 및 query-key-factory 적용
