### ISSUE TITLE
💡[Feature] 캘린더에서 선택한 날짜의 전시회에 대한 기록 추가 구현

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Frontend#80]
## ✨ 이슈 체크리스트

- [x] 이슈 제목: [Feature] '기능 내용 상세'
- [x] Assignees, Label 추가

## 💡 기능 개요

- 캘린더에서 선택한 날짜의 전시회에 대한 기록 추가 구현

## 📝 기능 상세 내용

- 캘린더에서 선택한 날짜의 전시회에 대한 기록 추가 구현

## ✅ TODO

- [x] 캘린더에서 선택한 날짜의 전시회에 대한 기록 추가 구현
