### ISSUE TITLE
💡[Feature] 선택한 옵션 보여주기 기능

### ISSUE THREAD

**Issue by hiwon2** [Art-Diary/Frontend#86]
## ✨ 이슈 체크리스트

- [x] 이슈 제목: [Feature] '기능 내용 상세'
- [x] Assignees, Label 추가

## 💡 기능 개요

- 선택한 옵션 보여주기 기능

## 📝 기능 상세 내용

- 선택한 옵션 보여주기 기능
- 
## ✅ TODO

- [x] 선택한 옵션 보여주기 기능
