### ISSUE TITLE
🐞[Bug] 사용자 프로필 수정 중 전시 분야 목록에서 마지막 분야가 누락되는 문제 해결

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Frontend#88]
## 🚨 이슈 체크리스트

- [x] 이슈 제목: [BUG] '버그 내용 상세'
- [x] Assignees, Label 추가

## 🐞 버그 개요

- 사용자 프로필 수정 중 전시 분야 목록에서 마지막 분야가 누락되는 문제 해결

## 🐛 버그 상세 내용

- 사용자 프로필 수정 중 전시 분야 목록에서 마지막 분야가 누락되는 문제 해결

## ✅ TODO

- [ ] 사용자 프로필 수정 중 전시 분야 목록에서 마지막 분야가 누락되는 문제 해결
