### ISSUE TITLE
🔨[Refactor] 기록 목록에서 마지막 기록 삭제 시 그 전 기록이 보이도록 수정

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Frontend#89]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label 추가

## 🔨 리팩토링 개요

- 기록 목록에서 마지막 기록 삭제 시 그 전 기록이 보이도록 수정

## 📝 리팩토링 상세 내용

- 기록 목록에서 마지막 기록 삭제 시 그 전 기록이 보이도록 수정

## ✅ TODO

- [x] 기록 목록에서 마지막 기록 삭제 시 그 전 기록이 보이도록 수정
