### ISSUE TITLE
🔨[Refactor] 전시회 검색창 재사용 틀 분리

### ISSUE THREAD

**Issue by cofls980** [Art-Diary/Frontend#91]
## ♻️ 이슈 체크리스트

- [x] 이슈 제목: [Refactor] '리팩토링 내용 상세'
- [x] Assignees, Label 추가

## 🔨 리팩토링 개요

- 전시회 검색창 재사용 틀 분리

## 📝 리팩토링 상세 내용

- 전시회 검색창 재사용 틀 분리

## ✅ TODO

- [x] 전시회 검색창 재사용 틀 분리
